# Generated by Django 3.2.3 on 2021-05-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='my-awsom-post', max_length=255),
        ),
    ]
