# Generated by Django 3.2.3 on 2021-05-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_auto_20210526_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
